
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SLAVENORMAL_H
#define SLAVENORMAL_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 slaveNormal_valueRangeTest (UNS8 typeValue, void * value);
const indextable * slaveNormal_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data slaveNormal_Data;
extern UNS32 g_nSysTick;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 g_nRfuu8;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS16 g_nRufu16;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS32 g_nRufu32;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS64 g_nRufu64;		/* Mapped at index 0x2004, subindex 0x00*/
extern  UNS8 slaveNormal_obj1008[15];
#endif // SLAVENORMAL_H
