
/* File generated by gen_cfile.py. Should not be modified. */

#include "AnyId_FR321CO_Slave.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 HardParams_DeviceAddr = 0x1;		/* Mapped at index 0x2000, subindex 0x01 */
UNS8 HardParams_Bud = 0x0;		/* Mapped at index 0x2000, subindex 0x02 */
UNS8 HardParams_CanFilterMode = 0x0;		/* Mapped at index 0x2000, subindex 0x03 */
UNS16 HardParams_CanFilterIdLow = 0x0;		/* Mapped at index 0x2000, subindex 0x04 */
UNS16 HardParams_CanFilterIdHigh = 0x0;		/* Mapped at index 0x2000, subindex 0x05 */
UNS16 HardParams_CanFilterMaskIdLow = 0x0;		/* Mapped at index 0x2000, subindex 0x06 */
UNS16 HardParams_CanFilterMaskIdHigh = 0x0;		/* Mapped at index 0x2000, subindex 0x07 */
UNS16 HardParams_RfidRfu = 0x0;		/* Mapped at index 0x2000, subindex 0x08 */
UNS8 RfidParams_Protocol = 0x0;		/* Mapped at index 0x2001, subindex 0x01 */
UNS8 RfidParams_RBlkNum = 0x0;		/* Mapped at index 0x2001, subindex 0x02 */
UNS16 RfidParams_AutoAddr = 0x0;		/* Mapped at index 0x2001, subindex 0x03 */
UNS16 RfidParams_AutoLen = 0x0;		/* Mapped at index 0x2001, subindex 0x04 */
UNS8 RfidParams_InvtTim = 0x0;		/* Mapped at index 0x2001, subindex 0x05 */
UNS8 RfidParams_IdleTim = 0x0;		/* Mapped at index 0x2001, subindex 0x06 */
UNS8 RfidParams_KeepTim = 0x0;		/* Mapped at index 0x2001, subindex 0x07 */
UNS16 RfidParams_RfidRfu = 0x0;		/* Mapped at index 0x2001, subindex 0x08 */
UNS8 DeviceParams_TagOpState = 0x0;		/* Mapped at index 0x2002, subindex 0x01 */
UNS8 DeviceParams_OpDevice = 0x0;		/* Mapped at index 0x2002, subindex 0x02 */
UNS16 DeviceParams_OpAddr = 0x0;		/* Mapped at index 0x2002, subindex 0x03 */
UNS16 DeviceParams_OpLen = 0x0;		/* Mapped at index 0x2002, subindex 0x04 */
UNS32 DeviceParams_OpFrame0 = 0x0;		/* Mapped at index 0x2002, subindex 0x05 */
UNS32 DeviceParams_OpFrame1 = 0x0;		/* Mapped at index 0x2002, subindex 0x06 */
UNS32 DeviceParams_OpFrame2 = 0x0;		/* Mapped at index 0x2002, subindex 0x07 */
UNS32 DeviceParams_OpFrame3 = 0x0;		/* Mapped at index 0x2002, subindex 0x08 */
UNS32 DeviceParams_OpFrame4 = 0x0;		/* Mapped at index 0x2002, subindex 0x09 */
UNS32 DeviceParams_OpFrame5 = 0x0;		/* Mapped at index 0x2002, subindex 0x0A */
UNS32 DeviceParams_OpFrame6 = 0x0;		/* Mapped at index 0x2002, subindex 0x0B */
UNS32 DeviceParams_OpFrame7 = 0x0;		/* Mapped at index 0x2002, subindex 0x0C */
UNS32 DeviceParams_Rfu = 0x0;		/* Mapped at index 0x2002, subindex 0x0D */
UNS32 Tag15693_UidLow = 0x0;		/* Mapped at index 0x2003, subindex 0x01 */
UNS32 Tag15693_UidHigh = 0x0;		/* Mapped at index 0x2003, subindex 0x02 */
UNS32 Tag15693_Block0 = 0x0;		/* Mapped at index 0x2003, subindex 0x03 */
UNS32 Tag15693_Block1 = 0x0;		/* Mapped at index 0x2003, subindex 0x04 */
UNS32 Tag15693_Block2 = 0x0;		/* Mapped at index 0x2003, subindex 0x05 */
UNS32 Tag15693_Block3 = 0x0;		/* Mapped at index 0x2003, subindex 0x06 */
UNS32 Tag15693_Block4 = 0x0;		/* Mapped at index 0x2003, subindex 0x07 */
UNS32 Tag15693_Block5 = 0x0;		/* Mapped at index 0x2003, subindex 0x08 */
UNS32 Tag15693_Block6 = 0x0;		/* Mapped at index 0x2003, subindex 0x09 */
UNS32 Tag15693_Block7 = 0x0;		/* Mapped at index 0x2003, subindex 0x0A */
UNS8 Tag15693_15693Block[10];		/* Mapped at index 0x2003, subindex 0x0B */
UNS8 Tag15693Block[] =		/* Mapped at index 0x2004, subindex 0x01 - 0x40 */
  {
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0,	/* 0 */
    0x0	/* 0 */
  };
UNS8 ComData_OpState = 0x0;		/* Mapped at index 0x2100, subindex 0x01 */
UNS8 ComData_RcvBuffer[10];		/* Mapped at index 0x2100, subindex 0x02 */
UNS8 ComData_RspBuffer[10];		/* Mapped at index 0x2100, subindex 0x03 */
UNS8 ComData_TestState = 0x0;		/* Mapped at index 0x2100, subindex 0x04 */
UNS64 ComData_OkTick = 0x0;		/* Mapped at index 0x2100, subindex 0x05 */
UNS64 ComData_AlllTick = 0x0;		/* Mapped at index 0x2100, subindex 0x06 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 AnyId_FR321CO_Slave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 AnyId_FR321CO_Slave_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 AnyId_FR321CO_Slave_iam_a_slave = 1;

TIMER_HANDLE AnyId_FR321CO_Slave_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 AnyId_FR321CO_Slave_obj1000 = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1000_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 AnyId_FR321CO_Slave_obj1001 = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1001_callbacks[] = 
                     {
                       NULL,
                     };

                    subindex AnyId_FR321CO_Slave_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t AnyId_FR321CO_Slave_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 AnyId_FR321CO_Slave_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period. */
                    UNS32 AnyId_FR321CO_Slave_obj1006 = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1006_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1006[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1006 }
                     };

/* index 0x1007 :   Synchronous Window Length. */
                    UNS32 AnyId_FR321CO_Slave_obj1007 = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1007_callbacks[] = 
                     {
                       NULL,
                     };

                    subindex AnyId_FR321CO_Slave_Index1007[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1007 }
                     };

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 AnyId_FR321CO_Slave_obj1008[10];
                    subindex AnyId_FR321CO_Slave_Index1008[] = 
                     {
                       { RO, visible_string, 10, (void*)&AnyId_FR321CO_Slave_obj1008 }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 AnyId_FR321CO_Slave_obj1009[10];
                    subindex AnyId_FR321CO_Slave_Index1009[] = 
                     {
                       { RO, visible_string, 10, (void*)&AnyId_FR321CO_Slave_obj1009 }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 AnyId_FR321CO_Slave_obj100A[10];
                    subindex AnyId_FR321CO_Slave_Index100A[] = 
                     {
                       { RO, visible_string, 10, (void*)&AnyId_FR321CO_Slave_obj100A }
                     };

/* index 0x100C :   Guard Time. */
                    UNS16 AnyId_FR321CO_Slave_obj100C = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index100C_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index100C[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj100C }
                     };

/* index 0x100D :   Life Time Factor. */
                    UNS8 AnyId_FR321CO_Slave_obj100D = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index100D_callbacks[] = 
                     {
                       NULL,
                     };

                    subindex AnyId_FR321CO_Slave_Index100D[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj100D }
                     };

/* index 0x1012 :   TIME COB ID. */
                    UNS32 AnyId_FR321CO_Slave_obj1012 = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1012_callbacks[] = 
                     {
                       NULL,
                     };

                    subindex AnyId_FR321CO_Slave_Index1012[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1012 }
                     };

/* index 0x1013 :   High Resolution Timestamp. */
                    UNS32 AnyId_FR321CO_Slave_obj1013 = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1013_callbacks[] = 
                     {
                       NULL,
                     };

                    subindex AnyId_FR321CO_Slave_Index1013[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1013 }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 AnyId_FR321CO_Slave_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1016 = 0;
                    UNS32 AnyId_FR321CO_Slave_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 AnyId_FR321CO_Slave_obj1017 = 0;	/* 0 */

                    ODCallback_t AnyId_FR321CO_Slave_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 AnyId_FR321CO_Slave_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 AnyId_FR321CO_Slave_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 AnyId_FR321CO_Slave_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex AnyId_FR321CO_Slave_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 AnyId_FR321CO_Slave_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex AnyId_FR321CO_Slave_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 AnyId_FR321CO_Slave_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1400_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 AnyId_FR321CO_Slave_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1401_SYNC_start_value = 0x0;	/* 0 */
					ODCallback_t AnyId_FR321CO_Slave_Index1401_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 AnyId_FR321CO_Slave_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1402_SYNC_start_value = 0x0;	/* 0 */
					ODCallback_t AnyId_FR321CO_Slave_Index1402_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 AnyId_FR321CO_Slave_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1403_SYNC_start_value = 0x0;	/* 0 */
					ODCallback_t AnyId_FR321CO_Slave_Index1403_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    ODCallback_t AnyId_FR321CO_Slave_Index1600_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };

                    UNS32 AnyId_FR321CO_Slave_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_FR321CO_Slave_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    ODCallback_t AnyId_FR321CO_Slave_Index1601_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };

                    UNS32 AnyId_FR321CO_Slave_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_FR321CO_Slave_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1601[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1601[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1601[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1601[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1601[7] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    ODCallback_t AnyId_FR321CO_Slave_Index1602_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };

                    UNS32 AnyId_FR321CO_Slave_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_FR321CO_Slave_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    ODCallback_t AnyId_FR321CO_Slave_Index1603_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };

                    UNS32 AnyId_FR321CO_Slave_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_FR321CO_Slave_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 AnyId_FR321CO_Slave_obj1800_Transmission_Type = 0x01;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 AnyId_FR321CO_Slave_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 AnyId_FR321CO_Slave_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_FR321CO_Slave_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 AnyId_FR321CO_Slave_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_FR321CO_Slave_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_FR321CO_Slave_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t AnyId_FR321CO_Slave_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_FR321CO_Slave_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    ODCallback_t AnyId_FR321CO_Slave_Index1A00_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };

                    UNS32 AnyId_FR321CO_Slave_obj1A00[] = 
                    {
                      0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_FR321CO_Slave_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A00[7] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    ODCallback_t AnyId_FR321CO_Slave_Index1A01_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };

                    UNS32 AnyId_FR321CO_Slave_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_FR321CO_Slave_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A01[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A01[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A01[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A01[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    ODCallback_t AnyId_FR321CO_Slave_Index1A02_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };

                    UNS32 AnyId_FR321CO_Slave_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_FR321CO_Slave_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    ODCallback_t AnyId_FR321CO_Slave_Index1A03_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };

                    UNS32 AnyId_FR321CO_Slave_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_FR321CO_Slave_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_FR321CO_Slave_obj1A03[7] }
                     };

/* index 0x2000 :   Mapped variable HardParams */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj2000 = 8; /* number of subindex - 1*/
                    ODCallback_t HardParams_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj2000 },
                       { RW, uint8, sizeof (UNS8), (void*)&HardParams_DeviceAddr },
                       { RW, uint8, sizeof (UNS8), (void*)&HardParams_Bud },
                       { RW, uint8, sizeof (UNS8), (void*)&HardParams_CanFilterMode },
                       { RW, uint16, sizeof (UNS16), (void*)&HardParams_CanFilterIdLow },
                       { RW, uint16, sizeof (UNS16), (void*)&HardParams_CanFilterIdHigh },
                       { RW, uint16, sizeof (UNS16), (void*)&HardParams_CanFilterMaskIdLow },
                       { RW, uint16, sizeof (UNS16), (void*)&HardParams_CanFilterMaskIdHigh },
                       { RW, uint16, sizeof (UNS16), (void*)&HardParams_RfidRfu }
                     };

/* index 0x2001 :   Mapped variable RfidParams */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj2001 = 8; /* number of subindex - 1*/
                    ODCallback_t RfidParams_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj2001 },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidParams_Protocol },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidParams_RBlkNum },
                       { RW, uint16, sizeof (UNS16), (void*)&RfidParams_AutoAddr },
                       { RW, uint16, sizeof (UNS16), (void*)&RfidParams_AutoLen },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidParams_InvtTim },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidParams_IdleTim },
                       { RW, uint8, sizeof (UNS8), (void*)&RfidParams_KeepTim },
                       { RW, uint16, sizeof (UNS16), (void*)&RfidParams_RfidRfu }
                     };

/* index 0x2002 :   Mapped variable DeviceParams */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj2002 = 13; /* number of subindex - 1*/
                    ODCallback_t DeviceParams_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index2002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj2002 },
                       { RO, uint8, sizeof (UNS8), (void*)&DeviceParams_TagOpState },
                       { RW, uint8, sizeof (UNS8), (void*)&DeviceParams_OpDevice },
                       { RW, uint16, sizeof (UNS16), (void*)&DeviceParams_OpAddr },
                       { RW, uint16, sizeof (UNS16), (void*)&DeviceParams_OpLen },
                       { RW, uint32, sizeof (UNS32), (void*)&DeviceParams_OpFrame0 },
                       { RW, uint32, sizeof (UNS32), (void*)&DeviceParams_OpFrame1 },
                       { RW, uint32, sizeof (UNS32), (void*)&DeviceParams_OpFrame2 },
                       { RW, uint32, sizeof (UNS32), (void*)&DeviceParams_OpFrame3 },
                       { RW, uint32, sizeof (UNS32), (void*)&DeviceParams_OpFrame4 },
                       { RW, uint32, sizeof (UNS32), (void*)&DeviceParams_OpFrame5 },
                       { RW, uint32, sizeof (UNS32), (void*)&DeviceParams_OpFrame6 },
                       { RW, uint32, sizeof (UNS32), (void*)&DeviceParams_OpFrame7 },
                       { RW, uint32, sizeof (UNS32), (void*)&DeviceParams_Rfu }
                     };

/* index 0x2003 :   Mapped variable Tag15693 */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj2003 = 11; /* number of subindex - 1*/
                    ODCallback_t Tag15693_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index2003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj2003 },
                       { RO, uint32, sizeof (UNS32), (void*)&Tag15693_UidLow },
                       { RO, uint32, sizeof (UNS32), (void*)&Tag15693_UidHigh },
                       { RO, uint32, sizeof (UNS32), (void*)&Tag15693_Block0 },
                       { RO, uint32, sizeof (UNS32), (void*)&Tag15693_Block1 },
                       { RO, uint32, sizeof (UNS32), (void*)&Tag15693_Block2 },
                       { RO, uint32, sizeof (UNS32), (void*)&Tag15693_Block3 },
                       { RO, uint32, sizeof (UNS32), (void*)&Tag15693_Block4 },
                       { RO, uint32, sizeof (UNS32), (void*)&Tag15693_Block5 },
                       { RO, uint32, sizeof (UNS32), (void*)&Tag15693_Block6 },
                       { RO, uint32, sizeof (UNS32), (void*)&Tag15693_Block7 },
                       { RO, visible_string, 10, (void*)&Tag15693_15693Block }
                     };

/* index 0x2004 :   Mapped variable Tag15693Block */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj2004 = 64; /* number of subindex - 1*/
                    ODCallback_t Tag15693Block_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index2004[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj2004 },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[0] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[1] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[2] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[3] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[4] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[5] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[6] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[7] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[8] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[9] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[10] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[11] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[12] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[13] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[14] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[15] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[16] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[17] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[18] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[19] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[20] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[21] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[22] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[23] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[24] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[25] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[26] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[27] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[28] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[29] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[30] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[31] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[32] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[33] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[34] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[35] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[36] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[37] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[38] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[39] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[40] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[41] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[42] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[43] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[44] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[45] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[46] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[47] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[48] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[49] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[50] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[51] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[52] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[53] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[54] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[55] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[56] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[57] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[58] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[59] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[60] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[61] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[62] },
                       { RO, uint8, sizeof (UNS8), (void*)&Tag15693Block[63] }
                     };

/* index 0x2100 :   Mapped variable ComData */
                    UNS8 AnyId_FR321CO_Slave_highestSubIndex_obj2100 = 6; /* number of subindex - 1*/
                    ODCallback_t ComData_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_FR321CO_Slave_Index2100[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_FR321CO_Slave_highestSubIndex_obj2100 },
                       { RO, uint8, sizeof (UNS8), (void*)&ComData_OpState },
                       { RW, visible_string, 10, (void*)&ComData_RcvBuffer },
                       { RO, visible_string, 10, (void*)&ComData_RspBuffer },
                       { RW, uint8, sizeof (UNS8), (void*)&ComData_TestState },
                       { RO, uint64, sizeof (UNS64), (void*)&ComData_OkTick },
                       { RO, uint64, sizeof (UNS64), (void*)&ComData_AlllTick }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable AnyId_FR321CO_Slave_objdict[] = 
{
  { (subindex*)AnyId_FR321CO_Slave_Index1000,sizeof(AnyId_FR321CO_Slave_Index1000)/sizeof(AnyId_FR321CO_Slave_Index1000[0]), 0x1000},
  { (subindex*)AnyId_FR321CO_Slave_Index1001,sizeof(AnyId_FR321CO_Slave_Index1001)/sizeof(AnyId_FR321CO_Slave_Index1001[0]), 0x1001},
  { (subindex*)AnyId_FR321CO_Slave_Index1006,sizeof(AnyId_FR321CO_Slave_Index1006)/sizeof(AnyId_FR321CO_Slave_Index1006[0]), 0x1006},
  { (subindex*)AnyId_FR321CO_Slave_Index1007,sizeof(AnyId_FR321CO_Slave_Index1007)/sizeof(AnyId_FR321CO_Slave_Index1007[0]), 0x1007},
  { (subindex*)AnyId_FR321CO_Slave_Index1008,sizeof(AnyId_FR321CO_Slave_Index1008)/sizeof(AnyId_FR321CO_Slave_Index1008[0]), 0x1008},
  { (subindex*)AnyId_FR321CO_Slave_Index1009,sizeof(AnyId_FR321CO_Slave_Index1009)/sizeof(AnyId_FR321CO_Slave_Index1009[0]), 0x1009},
  { (subindex*)AnyId_FR321CO_Slave_Index100A,sizeof(AnyId_FR321CO_Slave_Index100A)/sizeof(AnyId_FR321CO_Slave_Index100A[0]), 0x100A},
  { (subindex*)AnyId_FR321CO_Slave_Index100C,sizeof(AnyId_FR321CO_Slave_Index100C)/sizeof(AnyId_FR321CO_Slave_Index100C[0]), 0x100C},
  { (subindex*)AnyId_FR321CO_Slave_Index100D,sizeof(AnyId_FR321CO_Slave_Index100D)/sizeof(AnyId_FR321CO_Slave_Index100D[0]), 0x100D},
  { (subindex*)AnyId_FR321CO_Slave_Index1012,sizeof(AnyId_FR321CO_Slave_Index1012)/sizeof(AnyId_FR321CO_Slave_Index1012[0]), 0x1012},
  { (subindex*)AnyId_FR321CO_Slave_Index1013,sizeof(AnyId_FR321CO_Slave_Index1013)/sizeof(AnyId_FR321CO_Slave_Index1013[0]), 0x1013},
  { (subindex*)AnyId_FR321CO_Slave_Index1017,sizeof(AnyId_FR321CO_Slave_Index1017)/sizeof(AnyId_FR321CO_Slave_Index1017[0]), 0x1017},
  { (subindex*)AnyId_FR321CO_Slave_Index1018,sizeof(AnyId_FR321CO_Slave_Index1018)/sizeof(AnyId_FR321CO_Slave_Index1018[0]), 0x1018},
  { (subindex*)AnyId_FR321CO_Slave_Index1200,sizeof(AnyId_FR321CO_Slave_Index1200)/sizeof(AnyId_FR321CO_Slave_Index1200[0]), 0x1200},
  { (subindex*)AnyId_FR321CO_Slave_Index1400,sizeof(AnyId_FR321CO_Slave_Index1400)/sizeof(AnyId_FR321CO_Slave_Index1400[0]), 0x1400},
  { (subindex*)AnyId_FR321CO_Slave_Index1401,sizeof(AnyId_FR321CO_Slave_Index1401)/sizeof(AnyId_FR321CO_Slave_Index1401[0]), 0x1401},
  { (subindex*)AnyId_FR321CO_Slave_Index1402,sizeof(AnyId_FR321CO_Slave_Index1402)/sizeof(AnyId_FR321CO_Slave_Index1402[0]), 0x1402},
  { (subindex*)AnyId_FR321CO_Slave_Index1403,sizeof(AnyId_FR321CO_Slave_Index1403)/sizeof(AnyId_FR321CO_Slave_Index1403[0]), 0x1403},
  { (subindex*)AnyId_FR321CO_Slave_Index1600,sizeof(AnyId_FR321CO_Slave_Index1600)/sizeof(AnyId_FR321CO_Slave_Index1600[0]), 0x1600},
  { (subindex*)AnyId_FR321CO_Slave_Index1601,sizeof(AnyId_FR321CO_Slave_Index1601)/sizeof(AnyId_FR321CO_Slave_Index1601[0]), 0x1601},
  { (subindex*)AnyId_FR321CO_Slave_Index1602,sizeof(AnyId_FR321CO_Slave_Index1602)/sizeof(AnyId_FR321CO_Slave_Index1602[0]), 0x1602},
  { (subindex*)AnyId_FR321CO_Slave_Index1603,sizeof(AnyId_FR321CO_Slave_Index1603)/sizeof(AnyId_FR321CO_Slave_Index1603[0]), 0x1603},
  { (subindex*)AnyId_FR321CO_Slave_Index1800,sizeof(AnyId_FR321CO_Slave_Index1800)/sizeof(AnyId_FR321CO_Slave_Index1800[0]), 0x1800},
  { (subindex*)AnyId_FR321CO_Slave_Index1801,sizeof(AnyId_FR321CO_Slave_Index1801)/sizeof(AnyId_FR321CO_Slave_Index1801[0]), 0x1801},
  { (subindex*)AnyId_FR321CO_Slave_Index1802,sizeof(AnyId_FR321CO_Slave_Index1802)/sizeof(AnyId_FR321CO_Slave_Index1802[0]), 0x1802},
  { (subindex*)AnyId_FR321CO_Slave_Index1803,sizeof(AnyId_FR321CO_Slave_Index1803)/sizeof(AnyId_FR321CO_Slave_Index1803[0]), 0x1803},
  { (subindex*)AnyId_FR321CO_Slave_Index1A00,sizeof(AnyId_FR321CO_Slave_Index1A00)/sizeof(AnyId_FR321CO_Slave_Index1A00[0]), 0x1A00},
  { (subindex*)AnyId_FR321CO_Slave_Index1A01,sizeof(AnyId_FR321CO_Slave_Index1A01)/sizeof(AnyId_FR321CO_Slave_Index1A01[0]), 0x1A01},
  { (subindex*)AnyId_FR321CO_Slave_Index1A02,sizeof(AnyId_FR321CO_Slave_Index1A02)/sizeof(AnyId_FR321CO_Slave_Index1A02[0]), 0x1A02},
  { (subindex*)AnyId_FR321CO_Slave_Index1A03,sizeof(AnyId_FR321CO_Slave_Index1A03)/sizeof(AnyId_FR321CO_Slave_Index1A03[0]), 0x1A03},
  { (subindex*)AnyId_FR321CO_Slave_Index2000,sizeof(AnyId_FR321CO_Slave_Index2000)/sizeof(AnyId_FR321CO_Slave_Index2000[0]), 0x2000},
  { (subindex*)AnyId_FR321CO_Slave_Index2001,sizeof(AnyId_FR321CO_Slave_Index2001)/sizeof(AnyId_FR321CO_Slave_Index2001[0]), 0x2001},
  { (subindex*)AnyId_FR321CO_Slave_Index2002,sizeof(AnyId_FR321CO_Slave_Index2002)/sizeof(AnyId_FR321CO_Slave_Index2002[0]), 0x2002},
  { (subindex*)AnyId_FR321CO_Slave_Index2003,sizeof(AnyId_FR321CO_Slave_Index2003)/sizeof(AnyId_FR321CO_Slave_Index2003[0]), 0x2003},
  { (subindex*)AnyId_FR321CO_Slave_Index2004,sizeof(AnyId_FR321CO_Slave_Index2004)/sizeof(AnyId_FR321CO_Slave_Index2004[0]), 0x2004},
  { (subindex*)AnyId_FR321CO_Slave_Index2100,sizeof(AnyId_FR321CO_Slave_Index2100)/sizeof(AnyId_FR321CO_Slave_Index2100[0]), 0x2100},
};

const indextable * AnyId_FR321CO_Slave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;*callbacks = AnyId_FR321CO_Slave_Index1000_callbacks; break;
		case 0x1001: i = 1;*callbacks = AnyId_FR321CO_Slave_Index1001_callbacks; break;
		case 0x1006: i = 2;/* *callbacks = AnyId_FR321CO_Slave_Index1006_callbacks; break;
		case 0x1007: i = 3;/* callbacks = AnyId_FR321CO_Slave_Index1007_callbacks; break;
		case 0x1008: i = 4;break;
		case 0x1009: i = 5;break;
		case 0x100A: i = 6;break;
		case 0x100C: i = 7;/* *callbacks = AnyId_FR321CO_Slave_Index100C_callbacks; break;
		case 0x100D: i = 8;/* *callbacks = AnyId_FR321CO_Slave_Index100D_callbacks;*/ break;
		case 0x1012: i = 9;*callbacks = AnyId_FR321CO_Slave_Index1012_callbacks; break;
		case 0x1013: i = 10;*callbacks = AnyId_FR321CO_Slave_Index1013_callbacks; break;
		case 0x1017: i = 11;*callbacks = AnyId_FR321CO_Slave_Index1017_callbacks; break;
		case 0x1018: i = 12;break;
		case 0x1200: i = 13;break;
		case 0x1400: i = 14;*callbacks = AnyId_FR321CO_Slave_Index1400_callbacks; break;
		case 0x1401: i = 15;*callbacks = AnyId_FR321CO_Slave_Index1401_callbacks; break;
		case 0x1402: i = 16;*callbacks = AnyId_FR321CO_Slave_Index1402_callbacks; break;
		case 0x1403: i = 17;*callbacks = AnyId_FR321CO_Slave_Index1403_callbacks; break;
		case 0x1600: i = 18;*callbacks = AnyId_FR321CO_Slave_Index1600_callbacks; break;
		case 0x1601: i = 19;*callbacks = AnyId_FR321CO_Slave_Index1601_callbacks; break;
		case 0x1602: i = 20;*callbacks = AnyId_FR321CO_Slave_Index1602_callbacks; break;
		case 0x1603: i = 21;*callbacks = AnyId_FR321CO_Slave_Index1603_callbacks; break;
		case 0x1800: i = 22;*callbacks = AnyId_FR321CO_Slave_Index1800_callbacks; break;
		case 0x1801: i = 23;*callbacks = AnyId_FR321CO_Slave_Index1801_callbacks; break;
		case 0x1802: i = 24;*callbacks = AnyId_FR321CO_Slave_Index1802_callbacks; break;
		case 0x1803: i = 25;*callbacks = AnyId_FR321CO_Slave_Index1803_callbacks; break;
		case 0x1A00: i = 26;*callbacks = AnyId_FR321CO_Slave_Index1A00_callbacks; break;
		case 0x1A01: i = 27;*callbacks = AnyId_FR321CO_Slave_Index1A01_callbacks; break;
		case 0x1A02: i = 28;*callbacks = AnyId_FR321CO_Slave_Index1A02_callbacks; break;
		case 0x1A03: i = 29;*callbacks = AnyId_FR321CO_Slave_Index1A03_callbacks; break;
		case 0x2000: i = 30;*callbacks = HardParams_callbacks; break;
		case 0x2001: i = 31;*callbacks = RfidParams_callbacks; break;
		case 0x2002: i = 32;*callbacks = DeviceParams_callbacks; break;
		case 0x2003: i = 33;*callbacks = Tag15693_callbacks; break;
		case 0x2004: i = 34;*callbacks = Tag15693Block_callbacks; break;
		case 0x2100: i = 35;*callbacks = ComData_callbacks; break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &AnyId_FR321CO_Slave_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status AnyId_FR321CO_Slave_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index AnyId_FR321CO_Slave_firstIndex = {
  13, /* SDO_SVR */
  0, /* SDO_CLT */
  14, /* PDO_RCV */
  18, /* PDO_RCV_MAP */
  22, /* PDO_TRS */
  26 /* PDO_TRS_MAP */
};

const quick_index AnyId_FR321CO_Slave_lastIndex = {
  13, /* SDO_SVR */
  0, /* SDO_CLT */
  17, /* PDO_RCV */
  21, /* PDO_RCV_MAP */
  25, /* PDO_TRS */
  29 /* PDO_TRS_MAP */
};

const UNS16 AnyId_FR321CO_Slave_ObjdictSize = sizeof(AnyId_FR321CO_Slave_objdict)/sizeof(AnyId_FR321CO_Slave_objdict[0]); 

CO_Data AnyId_FR321CO_Slave_Data = CANOPEN_NODE_DATA_INITIALIZER(AnyId_FR321CO_Slave);

